// SPDX-License-Identifier: Apache-2.0
// Stable per-app URLs via host header — app-scoped indirection.
//
// Routes requests to `{app-id}.{suffix}` (e.g.
// `a9de476a-....pandastack.ai`) to the app's CURRENT live sandbox +
// port, without requiring auth. The app UUID itself acts as the bearer
// credential — anyone with the URL can reach the app for its lifetime.
//
// Unlike the preview host (`{port}-{sandbox_id}.{suffix}`), this URL is
// addressed to the APP, not a sandbox. Because the sandbox lookup happens
// per request, the URL keeps working across blue-green deploys that swap
// the underlying sandbox (app-scoped indirection / stable URL).
//
// Enable by setting PANDASTACK_APP_HOST_SUFFIX (e.g. "pandastack.ai"). When
// unset, the middleware is a passthrough and appURL falls back to the
// path-based /v1/apps/{id}/proxy/ form.
//
// Routing example:
//
//	GET /         HTTP/1.1
//	Host: a9de476a-....pandastack.ai
//	↓ resolve app → current sandbox_id + port ↓
//	GET /v1/sandboxes/{sandbox_id}/proxy/{port}/
//	(delegated to v1Handler with synthetic admin identity)
package main

import (
	"context"
	"net/http"
	"os"
	"regexp"
	"strconv"
	"strings"
)

const appHostSuffixEnv = "PANDASTACK_APP_HOST_SUFFIX"

// appHostUUIDRe matches the leftmost host label as an app UUID. App IDs are
// generated by gen_random_uuid() so they are always lowercase canonical UUIDs.
var appHostUUIDRe = regexp.MustCompile(`^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$`)

// appHostSuffix returns the configured base suffix (e.g. "pandastack.ai"),
// lowercased and without a leading dot, or "" when unset.
//
// It falls back to PANDASTACK_PREVIEW_HOST_SUFFIX when PANDASTACK_APP_HOST_SUFFIX
// is unset: apps and raw-sandbox preview URLs share the same apex domain and
// wildcard/TLS, and the app router ({app-id}.<suffix>) coexists with the preview
// router ({port}-{sandbox}.<suffix>, fn-{uuid}.<suffix>) on it — a bare-UUID
// label routes to an app, everything else falls through. So enabling preview
// URLs is enough to also get stable app URLs, with no separate env var. Set
// PANDASTACK_APP_HOST_SUFFIX explicitly only to override the app domain.
func appHostSuffix() string {
	if v := normHostSuffix(os.Getenv(appHostSuffixEnv)); v != "" {
		return v
	}
	return normHostSuffix(os.Getenv(previewHostSuffixEnv))
}

// normHostSuffix lowercases, trims spaces, and drops any leading dot.
func normHostSuffix(s string) string {
	return strings.ToLower(strings.TrimSpace(strings.TrimPrefix(s, ".")))
}

// HostRouter wraps next so that requests whose Host header looks like
// `{app-id}.{suffix}` are diverted to v1Handler with the path rewritten
// to /v1/sandboxes/{current_sandbox}/proxy/{port}/{originalPath}.
//
// All other requests pass through to next unchanged. Runs OUTSIDE the auth
// chain — the app UUID is the bearer credential (matches the preview-host
// model).
func (a *appsAPI) HostRouter(next http.Handler) http.Handler {
	base := appHostSuffix()
	if base == "" {
		return next
	}
	// Match `.<suffix>`; the leftmost label is then the bare app UUID. We match
	// at the apex (no `.apps.` infix) so apps are served at `{id}.<suffix>`,
	// which is covered by the single-level `*.<suffix>` wildcard cert. The UUID
	// regex below is what keeps this safe: non-UUID labels (`api`, `app`,
	// `docs`, `www`, `{port}-{sandbox}`, `fn-{uuid}`, …) fail it and fall
	// through to the next handler untouched.
	dotSuffix := "." + base

	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		host := r.Host
		if i := strings.IndexByte(host, ':'); i >= 0 {
			host = host[:i]
		}
		host = strings.ToLower(host)
		if !strings.HasSuffix(host, dotSuffix) {
			next.ServeHTTP(w, r)
			return
		}
		label := host[:len(host)-len(dotSuffix)]
		// Reject multi-label app hosts (e.g. `foo.bar.pandastack.ai`) — the
		// single-level `*.<suffix>` wildcard cert wouldn't cover them anyway.
		if strings.ContainsRune(label, '.') {
			next.ServeHTTP(w, r)
			return
		}
		if !appHostUUIDRe.MatchString(label) {
			next.ServeHTTP(w, r)
			return
		}

		app, err := a.appByIDOnly(r.Context(), label)
		if err != nil {
			http.Error(w, "app not found", http.StatusNotFound)
			return
		}
		// Wake-on-request: a hibernated app is transparently restored (~1s)
		// before the request is forwarded. Per-app singleflight in wakeApp
		// dedupes concurrent wakes within this process.
		if app.Status == "hibernated" && app.SandboxID != "" {
			woken, werr := a.wakeApp(r.Context(), app)
			if werr != nil {
				a.log.Warn("apps: wake-on-request failed", "app_id", app.ID, "err", werr)
				http.Error(w, "app is waking up; retry shortly", http.StatusServiceUnavailable)
				return
			}
			app = woken
		}
		if app.SandboxID == "" || app.Status != "running" {
			http.Error(w, "app has no running deployment", http.StatusServiceUnavailable)
			return
		}
		a.noteAppActivity(app.ID)

		origPath := r.URL.Path
		if origPath == "" {
			origPath = "/"
		}
		newPath := "/v1/sandboxes/" + app.SandboxID + "/proxy/" + strconv.Itoa(app.Port) + origPath

		r2 := r.Clone(r.Context())
		r2.URL.Path = newPath
		r2.URL.RawPath = ""
		r2.RequestURI = ""
		// Synthetic admin identity. This middleware only ever rewrites to a
		// path of the exact shape /v1/sandboxes/{id}/proxy/{port}/... — it
		// cannot reach any other tenant-sensitive route. The app UUID is the
		// bearer credential (matches the preview-host model).
		r2.Header.Set("X-Fcs-Workspace", "admin")
		r2.Header.Set("X-Pandastack-User-Id", "_app-host")
		r2.Header.Set("X-Pandastack-Auth-Method", "app-host")
		r2.Header.Del("Authorization")
		r2.Header.Set("X-Forwarded-Host", r.Host)
		if r.TLS != nil || strings.EqualFold(r.Header.Get("X-Forwarded-Proto"), "https") {
			r2.Header.Set("X-Forwarded-Proto", "https")
		} else {
			r2.Header.Set("X-Forwarded-Proto", "http")
		}

		a.v1.ServeHTTP(w, r2)
	})
}

// appByIDOnly looks up an app by its UUID alone (no workspace scope). Used by
// the host router, where the app UUID itself is the bearer credential.
func (a *appsAPI) appByIDOnly(ctx context.Context, id string) (AppInfo, error) {
	row := a.db.QueryRowContext(ctx, `SELECT `+appColumns+` FROM apps WHERE id = $1`, id)
	return scanAppInfo(row)
}
