#!/usr/bin/env bash
# start-mac.sh — one-click local dev on Apple Silicon.
#
# Firecracker requires Linux + KVM. On an M-series Mac that means a Linux VM
# with nested virtualization. We use Lima (https://lima-vm.io/) to spin up an
# x86_64 Ubuntu 24.04 VM with TCG acceleration and run the full PandaStack
# (agent + api + dashboard + marketing + 1 baked template) inside it.
#
# Notes:
#   - This is x86_64-emulated on Apple Silicon, so boot times are slower than
#     native cloud hosts. Expect ~5-15s sandbox cold starts vs ~250ms on cloud.
#   - We do NOT install brew packages for you; you'll get a list to install if
#     anything's missing.
#
# Usage:
#   ./scripts/local/start-mac.sh [up|down|status|logs|reset]
#
#   up       (default) create the VM, install deps, deploy services, bake one template
#   down     stop & delete the VM
#   status   show VM + service status
#   logs     tail pandastack-agent logs from inside the VM
#   reset    destroy everything, including bind-mounted state
set -euo pipefail

CMD="${1:-up}"
VM_NAME="pandastack-local"

GREEN='\033[0;32m'; YELLOW='\033[0;33m'; RED='\033[0;31m'; NC='\033[0m'
step() { printf "\n${GREEN}┌─ %s${NC}\n" "$*"; }
warn() { printf "${YELLOW}!${NC} %s\n" "$*"; }
die()  { printf "${RED}✗${NC} %s\n" "$*" >&2; exit 1; }

[[ "$(uname)" == "Darwin" ]] || die "Mac only; on Linux use scripts/linux-local-e2e.sh or the Terraform envs under infra/terraform/envs/"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
LIMA_DIR="$REPO_ROOT/.lima"
TEMPLATE_FILE="$LIMA_DIR/$VM_NAME.yaml"

ensure_deps() {
  local missing=()
  command -v limactl >/dev/null || missing+=("lima")
  command -v qemu-system-x86_64 >/dev/null || missing+=("qemu")
  if [ ${#missing[@]} -gt 0 ]; then
    warn "Missing deps. Install with:"
    printf "    brew install %s\n" "${missing[@]}" >&2
    die  "Then re-run $0 $CMD"
  fi
}

write_lima_yaml() {
  mkdir -p "$LIMA_DIR"
  cat > "$TEMPLATE_FILE" <<YAML
# Auto-generated by scripts/local/start-mac.sh — do not edit by hand
# x86_64 Ubuntu 24.04 with KVM-in-TCG so Firecracker can run.
arch: "x86_64"
vmType: "qemu"
images:
  - location: "https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-amd64.img"
    arch: "x86_64"
cpus: 6
memory: "8GiB"
disk: "60GiB"
mounts:
  - location: "${REPO_ROOT}"
    mountPoint: "/workspace"
    writable: true
ssh:
  loadDotSSHPubKeys: true
containerd:
  system: false
  user: false
portForwards:
  - guestPortRange: [3000, 3000]
    hostPortRange: [3000, 3000]
  - guestPortRange: [3100, 3100]
    hostPortRange: [3100, 3100]
  - guestPortRange: [8080, 8080]
    hostPortRange: [8080, 8080]
  - guestPortRange: [9100, 9100]
    hostPortRange: [9100, 9100]
provision:
  - mode: system
    script: |
      #!/bin/bash
      set -euxo pipefail
      export DEBIAN_FRONTEND=noninteractive
      apt-get update
      apt-get install -y ca-certificates curl wget jq squashfs-tools iproute2 iptables uuid-runtime e2fsprogs sqlite3 caddy golang-go
      # node 22
      if ! command -v node >/dev/null 2>&1; then
        curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
        apt-get install -y nodejs
      fi
      # firecracker (x86_64, runs because VM is x86 even though host is arm64)
      if ! command -v firecracker >/dev/null 2>&1; then
        cd /tmp
        wget -q https://github.com/firecracker-microvm/firecracker/releases/download/v1.16.0/firecracker-v1.16.0-x86_64.tgz
        tar xf firecracker-v1.16.0-x86_64.tgz
        install -m 0755 release-v1.16.0-x86_64/firecracker-v1.16.0-x86_64 /usr/local/bin/firecracker
        install -m 0755 release-v1.16.0-x86_64/jailer-v1.16.0-x86_64 /usr/local/bin/jailer
      fi
      # group/state dirs
      groupadd -f kvm
      install -d -m 0755 /var/lib/pandastack /var/lib/fcsandbox/{kernels,templates,vms,snapshots} /run/fcsandbox /etc/pandastack /etc/caddy /opt/pandastack-dashboard /opt/pandastack-marketing
      sysctl -w net.ipv4.ip_forward=1
      echo "net.ipv4.ip_forward=1" > /etc/sysctl.d/99-pandastack.conf
probes:
  - script: |
      #!/bin/bash
      set -e
      command -v firecracker
      command -v node
      command -v go
YAML
}

case "$CMD" in
  up)
    ensure_deps
    write_lima_yaml

    if ! limactl list --format '{{.Name}}' 2>/dev/null | grep -qx "$VM_NAME"; then
      step "Creating Lima VM ($VM_NAME)"
      limactl create --name "$VM_NAME" --tty=false "$TEMPLATE_FILE"
    fi
    if [[ "$(limactl list --format '{{.Status}}' "$VM_NAME" 2>/dev/null || echo Stopped)" != "Running" ]]; then
      step "Starting VM"
      limactl start --tty=false "$VM_NAME"
    fi

    step "Building binaries inside the VM"
    limactl shell "$VM_NAME" -- bash -lc '
      set -e
      cd /workspace/agent && go build -o /tmp/pandastack-agent ./cmd/agent
      cd /workspace/api   && go build -o /tmp/pandastack-api   ./cmd/api
      sudo install -m 0755 /tmp/pandastack-agent /usr/local/bin/pandastack-agent
      sudo install -m 0755 /tmp/pandastack-api   /usr/local/bin/pandastack-api
    '

    step "Writing /etc/pandastack/env (local SQLite, no Supabase)"
    limactl shell "$VM_NAME" -- sudo tee /etc/pandastack/env >/dev/null <<'ENV'
PANDASTACK_DB_DRIVER=sqlite
PANDASTACK_DB_DSN=/var/lib/pandastack-io/pandastack-ai-oss.db
PANDASTACK_NATID=1
PANDASTACK_NATID_POOL_SIZE=4
PANDASTACK_DEFAULT_TTL_SECONDS=300
PANDASTACK_METRICS_LISTEN=:9100
PANDASTACK_AUTH_SKIP_PREFIXES=/healthz,/version,/metrics,/v1/metrics,/v1/
ENV

    step "Installing systemd units"
    limactl shell "$VM_NAME" -- sudo tee /etc/systemd/system/pandastack-agent.service >/dev/null <<'UNIT'
[Unit]
Description=Pandastack Firecracker agent
After=network-online.target
[Service]
Type=simple
EnvironmentFile=/etc/pandastack/env
ExecStart=/usr/local/bin/pandastack-agent -socket /run/fcsandbox/agent.sock -data-dir /var/lib/pandastack -db /var/lib/pandastack-io/pandastack-ai-oss.db
Restart=always
RestartSec=3
[Install]
WantedBy=multi-user.target
UNIT
    limactl shell "$VM_NAME" -- sudo tee /etc/systemd/system/pandastack-api.service >/dev/null <<'UNIT'
[Unit]
Description=Pandastack public API (local, no auth)
After=pandastack-agent.service
[Service]
Type=simple
EnvironmentFile=/etc/pandastack/env
ExecStart=/usr/local/bin/pandastack-api -addr :8080 -agent-socket /run/fcsandbox/agent.sock -token-file /var/lib/pandastack/tokens.json
Restart=always
RestartSec=3
[Install]
WantedBy=multi-user.target
UNIT
    limactl shell "$VM_NAME" -- sudo systemctl daemon-reload
    limactl shell "$VM_NAME" -- sudo systemctl enable --now pandastack-agent pandastack-api

    step "Building + deploying dashboard"
    limactl shell "$VM_NAME" -- bash -lc '
      cd /workspace/dashboard && npm ci --no-audit --no-fund && npm run build
      sudo rsync -a --delete .next public package.json package-lock.json /opt/pandastack-dashboard/
      cd /opt/pandastack-dashboard && sudo npm ci --omit=dev --silent --no-audit --no-fund
    '
    limactl shell "$VM_NAME" -- sudo tee /etc/systemd/system/pandastack-dashboard.service >/dev/null <<'UNIT'
[Unit]
Description=Pandastack dashboard
After=network-online.target
[Service]
Type=simple
WorkingDirectory=/opt/pandastack-dashboard
Environment=NEXT_PUBLIC_API_URL=http://localhost:8080/v1
ExecStart=/usr/bin/npm run start -- --hostname 0.0.0.0 --port 3000
Restart=always
RestartSec=3
[Install]
WantedBy=multi-user.target
UNIT
    limactl shell "$VM_NAME" -- sudo systemctl daemon-reload
    limactl shell "$VM_NAME" -- sudo systemctl enable --now pandastack-dashboard

    step "Smoke test"
    sleep 5
    curl -fsS http://localhost:8080/healthz && echo "  api OK"

    cat <<EOF

$(printf "${GREEN}╰─ Local PandaStack is up${NC}")
  Dashboard:  http://localhost:3000
  API:        http://localhost:8080/v1/sandboxes  (no auth in local mode)
  Metrics:    http://localhost:9100/metrics

  Drop into the VM:   limactl shell $VM_NAME
  Stop:               $0 down
  Bake a template:    limactl shell $VM_NAME -- sudo bake-templates code-interpreter

EOF
    ;;

  down)
    step "Stopping + deleting VM"
    limactl stop "$VM_NAME" 2>/dev/null || true
    limactl delete --force "$VM_NAME" 2>/dev/null || true
    ;;

  status)
    limactl list "$VM_NAME" || echo "VM not present"
    limactl shell "$VM_NAME" -- sudo systemctl status pandastack-agent pandastack-api pandastack-dashboard --no-pager 2>/dev/null || true
    ;;

  logs)
    limactl shell "$VM_NAME" -- sudo journalctl -u pandastack-agent -u pandastack-api -f
    ;;

  reset)
    "$0" down
    rm -rf "$LIMA_DIR"
    ;;

  *) die "unknown command: $CMD (use up|down|status|logs|reset)" ;;
esac
