app = "pandastack-agent-single-node"
primary_region = "ord"

[build]
  image = "ghcr.io/pandastack-io/pandastack-ai/agent:latest"

[env]
  PANDASTACK_CONTROL_PLANE_URL = "https://api.pandastack.ai"

[[vm]]
  cpu_kind = "performance"
  cpus = 4
  memory = "8192mb"
